version: '3.8'
services:
  db_postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - ${DB_DOCKER_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - TZ=Asia/Jakarta
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
volumes:
  data: {}
